### ISSUE TITLE
can i use it with swift type? 

### ISSUE THREAD

**Issue by ipeisong** [nicklockwood/FastCoding#12]
for example, string, array? thanks.

**Comment by Birju-Bhatt** [comment]
class func query() -> String {
        
        let keys = self.fastCodingKeys().map{ $0 as! String } // **error: Cast from '[Any]' to unrelated type 'String' always fails**
        let keysToIgnore = self.ignoredDBField()
        let finalKeys = keys.filter{!keysToIgnore.contains($0)} // **error: Cannot convert value of type 'Character' to expected argument type 'String'**

        let arrWithType = finalKeys.map({ (key) -> String in
            return key.appending(" TEXT")
        })
        let query = arrWithType.joined(separator: ",")

        print(query)
        return query
    }

I want to use it in swift 4.1 using Xcode 10. And i got that error. Please help me out for that issue.
Thanks in Advance.

**Comment by nicklockwood** [comment]
@Birju-Bhatt since FastCoding isn’t annotated for nullability, you’ll need to unwrap fastCodingKeys with !

`self.fastCodingKeys()!.map{ $0 as! String }`

**Comment by Birju-Bhatt** [comment]
Hi Nick,
Thank you for your immediate response. I will take care of this. Your solution is working like charm.

**Comment by Tapansinh** [comment]
> @Birju-Bhatt since FastCoding isn’t annotated for nullability, you’ll need to unwrap fastCodingKeys with !
> 
> `self.fastCodingKeys()!.map{ $0 as! String }`

it returns me null keys for Xcode 11 while it's working perfectly with older Xcode 10. But when I changed the type to NSString from String, it works! Any solution to make it work for swift projects?

here is my model,

class Tables: NSObject {
    @objc var table_name: String?
    @objc var timestamp: String?
}

Any help is appreciated.
