### ISSUE TITLE
remove Object from NSData

### ISSUE THREAD

**Issue by gitabdelkarim** [nicklockwood/FastCoding#17]
How can i remove an object i saved : 

     NSString *path = [[[self class] documentsDirectory]      stringByAppendingPathComponent:@"Establishment.reservation"];
     NSData *data = [FastCoder dataWithRootObject:self];
     [data writeToFile:path atomically:YES];

**Comment by nicklockwood** [comment]
[[[NSFileManager] defaultManager] removeItemAtPath:path error:NULL];

**Comment by Martusenko** [comment]
writeToFile:atomically: will write/overwrite “Establishment.reservation” file with archived data.

so just remove your file with removeItemAtPath:error: to remove this object

Serge.

**Comment by gitabdelkarim** [comment]
Thanks, i wanted to completely remove the object so i used : 
[[NSFileManager defaultManager] removeItemAtPath:path error:NULL];
