### ISSUE TITLE
Exception rasied if modified the class's property

### ISSUE THREAD

**Issue by smalllixin** [nicklockwood/FastCoding#18]
Hi nick,
     I am trying to adopt fastcoding lib. I found if the class property deleted or renamed will get a entire uninitialized object.
    The reason I found setValue to a non existed property will raise an exception:
``` ObjC
    for (__unsafe_unretained NSString *key in definition->_propertyKeys)
    {
            [object setValue:FCReadObject(decoder) forKey:key];
    }
``` 
The quick fix is add a try-catch to prevent the exception. 
``` ObjC
    for (__unsafe_unretained NSString *key in definition->_propertyKeys)
    {
        @try {
            [object setValue:FCReadObject(decoder) forKey:key];
        }
        @catch (NSException *exception) {
            
        }
    }
```
However if there is another better solution?

**Comment by nicklockwood** [comment]
You could override setValue:forUndefinedKey: on your class and have it do nothing instead of crashing.

**Comment by smalllixin** [comment]
Wow, this feels better. Thank u.
