### ISSUE TITLE
FastCoding fails to decode NSColorSpace properly

### ISSUE THREAD

**Issue by adamwulf** [nicklockwood/FastCoding#30]
I've submitted a unit test with pull request #29 

I've stepped through the reading and writing functions, and FCReadNSCodedObject is pulling out the correct properties and keys into `decoder->_properties` but the `FC_AUTORELEASE([[NSClassFromString(className) alloc] initWithCoder:decoder])` line still builds an invalid `NSColorSpace` for some reason. It's not clear to me why it's breaking.

**Comment by nicklockwood** [comment]
Thanks for the test case! This is fixed in version 3.3.
